server:
  port: 80
spring:
  application:
    name: e-commerce-consumer-openfeign
#配置eureka-client
eureka:
  client:
    register-with-eureka: true #将自己注册到eureka-client
    fetch-registry: true #可以从eureka拉去需要的远程接口
    service-url:
      #将本服务注册到EurekaServer 集群  使用逗号间隔
      defaultZone: http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka

#logging:
#  level:
#  #对MemberFeignService 接口调用 打印信息Debug
#   com.hspedu.springcloud.service.MemberFeignService: debug
#ribbon:
#  # 设置feign客户端超时时间 (openfeign默认支持ribbon)
#  # ReadTimeout: 8000 建立连接从服务提供方获取到可用资源的全部时间
#  ReadTimeout: 8000
#  #两端连接所用的时间
#  Connection: 8000