server:
  port: 80
spring:
  application:
    name: member-serivce-consumer-80
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
#配置eureka-client
eureka:
  client:
    register-with-eureka: true #将自己注册到eureka-client
    fetch-registry: true
    service-url:
      #将本服务注册到EurekaServer 集群  使用逗号间隔
      defaultZone: http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka

